### PR TITLE
Update to version 4.6.x of NuGet

### PR DESCRIPTION
**Pull request by bjorkstromm**
Merge branch `release-4.6.1-rtm` from https://github.com/NuGet/NuGet.Client

Haven't had time to test this out yet.

### CODE REVIEW

**Comment by aelij** [comment]
Haha, I'm obviously no going to go through all of these changes. :) Please test it and let me know, then I'll update the NuGet package. Thanks!

**Comment by bjorkstromm** [comment]
@aelij tested using Cake. Works like a charm, great perf improvements with regards to dependency resolution!

**Comment by aelij** [comment]
The package has been pushed (being indexed right now).

**Comment by bjorkstromm** [comment]
Thank you!

**Pull request merged**
