### PR TITLE
Netstandard 4.9.2

### PR DESCRIPTION
**Pull request by devlead**
Merge upstream changes from 4.9.2

### CODE REVIEW

**Comment by aelij** [comment]
Hey @devlead. Since I'm no longer using this package, maybe would you'd like to move this fork to the Cake org? (I don't mind keeping it here, I thought it might be more convenient for you guys). I can also give you ownership of the package (I'd already give it to @mholo65).

Also, maybe it's time to try submitting a PR in the original repo again ;)

**Comment by devlead** [comment]
Best would be upstream netstandard support, wonder if this is what NuGet/NuGet.Client#2011 aims to solve, last updated June, so not too long ago ;)

**Comment by bjorkstromm** [comment]
@aelij we are in the position of transitioning away from depending on `NuGet.PackageManagement` and instead just use `NuGet.Packaging` and `NuGet.Protocol` (and friends) for installing packages. Hopefully, this will be our last "unofficial" release of `NuGet.PackageManagement.NetStandard`. We could look at moving, if we need to update this again?

**Comment by aelij** [comment]
Whatever you decide is fine by me. BTW I've also moved to a different API (NuGet.Commands) using lock files for restoring packages in RoslynPad:
https://github.com/aelij/RoslynPad/commit/f49711aa8607f8e5df6e3472deff2061ba310b76#diff-742d5dc1aedc10de78a5ffdb98249a01

**Comment by bjorkstromm** [comment]
Thanks! I’ve also looked into `NuGet.Commands`, but since `NuGet.ProjectModel` is one of the reasons I like to switch away from `NuGet.PackageManagement` I tried to go even lower. I even wrote a (rather lengty) blog post on my journey, here https://martinbjorkstrom.com/posts/2018-09-19-revisiting-nuget-client-libraries if you’re interested :smile:

**Comment by aelij** [comment]
Nice! Can't find this stuff anywhere else.
For me the `RestoreCommand` works really well since I need the reference paths. I basically replaced MSBuild restore with a design-time `#r` experience. But I can understand why you wanted to move away from project model.

**Pull request merged**
